let usuarios = [
  {
    _id: 'h1',
    nome: 'Caio',
    email: 'c@c',
    senha: '123',
    sexo: 'masculino',
    foto: 'h1.jpg',
    telefone: '2277778888',
    likedList: ['a', 'b', 'c', 'g', 'jessica-hartel'],
    dislikedList: ['d', 'e'],
  },
  {
    _id: 'a',
    sexo: 'feminino',
    nome: 'Fernanda',
    foto: 'a.jpg',
    telefone: '2244445555',
    likedList: ['h1'],
    dislikedList: ['d', 'e'],
  },
  {
    _id: 'b',
    sexo: 'feminino',
    nome: 'Andreia',
    foto: 'b.jpg',
    telefone: '12341234',
    likedList: ['h1'],
    dislikedList: [],
  },
  {
    _id: 'c',
    sexo: 'feminino',
    nome: 'Andressa',
    foto: 'c.jpg',
    telefone: '55556666',
    likedList: [],
    dislikedList: [],
  },
  {
    _id: 'd',
    sexo: 'feminino',
    nome: 'Alessandra',
    foto: 'd.jpg',
    telefone: '99998888',
    likedList: [],
    dislikedList: [],
  },
  {
    _id: 'e',
    sexo: 'feminino',
    nome: 'Amanda',
    foto: 'e.jpg',
    telefone: '12344321',
    likedList: [],
    dislikedList: [],
  },
  {
    _id: 'f',
    sexo: 'feminino',
    nome: 'Leandra',
    foto: 'f.jpg',
    telefone: '567887654',
    likedList: [],
    dislikedList: [],
  },
  {
    _id: 'g',
    sexo: 'feminino',
    nome: 'Zoe',
    senha: 'abc',
    email: 'zoe@email',
    foto: 'g.jpg',
    telefone: '98671523',
    likedList: [],
    dislikedList: [],
  },
  {
    _id: 'h',
    sexo: 'feminino',
    nome: 'Nataly',
    foto: 'h.jpg',
    telefone: '12344321',
    likedList: [],
    dislikedList: [],
  },
  {
    _id: 'jessica-hartel',
    sexo: 'feminino',
    nome: 'Jessica Hartel',
    foto: 'jessica-hartel.jpg',
    telefone: '98987755',
    likedList: ['h1'],
    dislikedList: [],
  },
]

module.exports = usuarios